name: Keepalive Workflow

on:
  schedule:
    # 매월 1일 00:00 UTC에 실행
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          time_elapsed: 45
